apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-http-errors
  namespace: observability
spec:
  description: ""
  indicator:
    latency:
      success:
        metric: http_server_duration_bucket{le="0.032", http_status_code=~"4.."}
      total:
        metric: http_server_duration_count
  target: "99.9"
  window: 2w

