apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: bufsandboxd
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  target: '99.0'
  window: 7d
  indicator:
    ratio:
      errors:
        metric: http_server_duration_count{http_server_name="bufsandboxd", http_status_code=~"5.."}
      total:
        metric: http_server_duration_count{http_server_name="bufsandboxd"}
