{
 "title": "Pyrra - rpc_server_duration_count_slo",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "rpc_service", "label": "rpc_service", "query": { "query": "label_values(rpc_service)" } },
   { "name": "rpc_method", "label": "rpc_method", "query": { "query": "label_values(rpc_method)" } }
  ]
 },
 "panels": [
  {
   "title": "Objective",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "0.99", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Window",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "2592000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (sum(rpc_server_duration:increase30d{rpc_connect_rpc_error!=\"\",rpc_method=~\"$rpc_method\",rpc_service=~\"$rpc_service\"} or vector(0)) / sum(rpc_server_duration:increase30d{rpc_method=~\"$rpc_method\",rpc_service=~\"$rpc_service\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(((1 - (sum(rpc_server_duration:increase30d{rpc_connect_rpc_error!=\"\",rpc_method=~\"$rpc_method\",rpc_service=~\"$rpc_service\"} or vector(0)) / sum(rpc_server_duration:increase30d{rpc_method=~\"$rpc_method\",rpc_service=~\"$rpc_service\"}))) - (0.99))) / (1 - (0.99))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(((1 - (sum(rpc_server_duration:increase30d{rpc_connect_rpc_error!=\"\",rpc_method=~\"$rpc_method\",rpc_service=~\"$rpc_service\"} or vector(0)) / sum(rpc_server_duration:increase30d{rpc_method=~\"$rpc_method\",rpc_service=~\"$rpc_service\"}))) - (0.99))) / (1 - (0.99))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(sum(rpc_server_duration_count{rpc_method=~\"$rpc_method\",rpc_service=~\"$rpc_service\"})[$__rate_interval:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(sum(rpc_server_duration_count{rpc_connect_rpc_error!=\"\",rpc_method=~\"$rpc_method\",rpc_service=~\"$rpc_service\"} or vector(0))[$__rate_interval:]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}